### ISSUE TITLE
Got this issue in the Fluentd pod log( fluentd version 1.11.1)  warning: 299 Elasticsearch-7.9.2-d34da0ea4a966c4e49417f2da2f244e3e97b4e6e "[types removal] Specifying types in bulk requests is deprecated."

### ISSUE THREAD

**Issue by SureshProgrammer** [kokuwaio/helm-charts#10]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
please put the output of it here
```

Kubernetes Version:

```console
$ kubectl version
please put the output of it here
```

**Which version of the chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```
key: value
```

```
helm install my-release {{ .GitHubOrg }}/name-of-chart --version version --values values.yaml
```

-->

**Anything else we need to know**:

**Comment by SureshProgrammer** [comment]
/usr/local/bundle/gems/fluentd-1.11.1/lib/fluent/plugin_helper/http_server/compat/server.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/fluentd-1.11.1/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here
warning: 299 Elasticsearch-7.9.2-d34da0ea4a966c4e49417f2da2f244e3e97b4e6e "[types removal] Specifying types in bulk requests is deprecated."
warning: 299 Elasticsearch-7.9.2-d34da0ea4a966c4e49417f2da2f244e3e97b4e6e "[types removal] Specifying types in bulk requests is deprecated."
warning: 299 Elasticsearch-7.9.2-d34da0ea4a966c4e49417f2da2f244e3e97b4e6e "[types removal] Specifying types in bulk requests is deprecated."

**Comment by monotek** [comment]
Please use search function: https://github.com/kokuwaio/helm-charts/issues/3
