### ISSUE TITLE
Creating Empty Indexes when enabled the ILM

### ISSUE THREAD

**Issue by yphanikumar1995** [kokuwaio/helm-charts#143]
**Describe the bug**
We enabled the ILM , We given retention period 14 days but it is created the many empty indexes  and those empty indexes not deleting after 14 days
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/81069965/210779516-0335e336-1e99-42fb-b02c-270b6b73abb2.png">

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
v3.3.4
```

Kubernetes Version:

```console
$ kubectl version
 v1.23.12
```

**Which version of the chart**: 13.2.0

**What happened**: Creating empty indexes and not deleting after retention period.

**What you expected to happen**:  Shouldn't create empty indexes , if create empty indexes , it should delete after retention period.

**How to reproduce it** (as minimally and precisely as possible): Enable ILM and check

values.yaml 

```
elasticsearch:
  ilm:
    enabled: true
    policy_overwrite: true
    policy:
      phases:
        hot:
          min_age: 0ms
          actions:
            rollover:
              max_age: 1d
              max_size: 20gb
            set_priority:
                priority: 100
        delete:
          min_age: 14d
          actions:
            delete: {}
  template:
    enabled: true
    overwrite: true
    useLegacy: true
    name: fluentd-template
    file: fluentd-template.json
    content: |-
      {
        "index_patterns": [
            "logstash-*"
        ],
        "settings": {
            "index": {
                "number_of_replicas": "1"
            }
        }
      }
```

```
helm install my-release {{ .GitHubOrg }}/name-of-chart --version version --values values.yaml
```

**Anything else we need to know**:

**Comment by monotek** [comment]
Please ask questions about I'm in the kibana repo
