### ISSUE TITLE
[fluentd-elasticsearch] invalid application version for chart version 10.2.0

### ISSUE THREAD

**Issue by tpokki** [kokuwaio/helm-charts#18]
**Describe the bug**
Invalid version for fluentd-elasticsearch chart version 10.2.0

```
$ helm search repo kokuwa/fluentd-elasticsearch
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION
kokuwa/fluentd-elasticsearch	10.2.0       	3.1.0      	A Fluentd Helm chart for Kubernetes with Elasti...

$ helm template kokuwa/fluentd-elasticsearch --version 10.2.0|grep fluentd:v
        image:  "quay.io/fluentd_elasticsearch/fluentd:v3.0.5"
```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

**Which version of the chart**: 
10.2.0

**What happened**:
Got fluentd_elasticsearch/fluentd image version v3.0.5

**What you expected to happen**:
Expected fluentd_elasticsearch/fluentd image version v3.1.0

**How to reproduce it** (as minimally and precisely as possible):
See description.

**Comment by monotek** [comment]
Oops. Seemed the file was not checked in. I'll fix it tomorrow.

**Comment by monotek** [comment]
will be fixed with: https://github.com/kokuwaio/helm-charts/pull/19
