### ISSUE TITLE
fluentd: apiVersion of DaemonSet is extensions/v1beta1 when deploying with Helm3

### ISSUE THREAD

**Issue by BernhardBerbuir** [kokuwaio/helm-charts#21]
**Describe the bug**
When deploying fluentd with Helm 3 to a Kubernetes cluster with a version newer than 1.9
than the `apiVersion` of the `DaemonSet` should be `apps/v1` instead of `extensions/v1beta1`.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
10.2.0

**What happened**:
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
```

**What you expected to happen**:
```yaml
apiVersion: apps/v1
kind: DaemonSet
```

**How to reproduce it** (as minimally and precisely as possible):

Use Helm3 for deploying fluentd to a Kubernetes cluster with a version newer than 1.9

**Anything else we need to know**:

The Helm `capabilities` have been changed (see [capabilities.go](https://github.com/helm/helm/blob/master/pkg/chartutil/capabilities.go)).
I assume that for most users it would be ok to support only Kubernetes versions newer than 1.9.

**Comment by monotek** [comment]
Will be fixed in https://github.com/kokuwaio/helm-charts/pull/22

**Comment by BernhardBerbuir** [comment]
@monotek : The fix is problematic as there is no migration path available. The old chart version `10.*` does not support Kubernetes `1.16` and the new chart version `11.*` requires at least Kubernetes version `1.16`. At least on Kubernetes version should be supported by both versions (preferable by the new one).

Increasing the required Kubernetes version from 1.9 to 1.16 is an extrem fast-forward approach. It looks like the `PodSecurityPolicy` is the reason for this change. I understand that the version checks in the Helm templates are ugly, but re-adding this check would provide a better user experience.

**Comment by monotek** [comment]
The old 10.x version of the chart does support k8s 1.16+ if you use helm 2.

Kubernetes 1.16 is already end of life so i don't see why we should support the old versions any longer. See: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

Our test infra also uses 1.16 as oldest version too. See: https://github.com/kokuwaio/helm-charts/blob/main/.github/workflows/ci.yaml#L70

Helm 2 is also deprecated on November 13 so if you're a helm 2 user you can still use the chart with version 10.2.1, which is feature par with 11.0.1. See: https://helm.sh/blog/helm-v2-deprecation-timeline/

extensions/v1beta1 was suported up to kubernetes 1.15 and the the podsecuritypolicy is also not enabled by default, so you could still use the chart with helm 3, disabling the psp.

If you need to use Helm 3 and k8s 1.16+ use chart version 1.11.x.
