### ISSUE TITLE
Add possibility to inject self-managed side-cars

### ISSUE THREAD

**Issue by Alien2150** [kokuwaio/helm-charts#25]
**Is your feature request related to a problem? Please describe.**
It would be helpful to add a possibility to inject self-managed sidecar containers (e.g fluentd-ui) into the daemonset. At the moment there is only 1 fixed sidecar container (es-proxy).

**Describe the solution you'd like**
 Add possibility to inject self-managed side-cars

**Describe alternatives you've considered**
Of course it would also be possible to write my own template. But it's way more tricky to get it running properly (As there are more network hops when local-host cannot be used).

**Additional context**

**Comment by tillig** [comment]
This would also be helpful when configuring Fluentd to use Istio-generated certificates - you inject the sidecar into the Fluentd pod and have it read the certificate files from a common mount point.
