### ISSUE TITLE
Additional PrometheusRules regarding errors

### ISSUE THREAD

**Issue by desaintmartin** [kokuwaio/helm-charts#30]
Hello guys,
I've spent a few hours digging into fluentd not being able to push to Elasticsearch for some unrelated reasons.
I'm thinking about adding a few PrometheusRules, and here would be the best place.
Have you experimented about rules based on things like:
```
increase(fluentd_status_retry_count[10m]) > 0
increase(fluentd_output_status_num_errors[10m]) > 0
```
?
Unfortunately, it does NOT catch all errors but this is a start.
What would be your opinion on such things? I'm planning to add them on our clusters and see the result.

**Comment by monotek** [comment]
A PR for this would be very welcome :)
