### ISSUE TITLE
mysqldump chart creating unneccessary secret

### ISSUE THREAD

**Issue by Anticom** [kokuwaio/helm-charts#39]
**Describe the bug**
When using the `mysqldump` chart (Version 4.0.0) and configuring it like so:
```yaml
mysql:
  host: my-release-mysql
  existingSecret: my-release-mysql
  existingSecretKey: mysql-root-password
```
it still generates a Secret from `mysqldump/templates/secret-mysql.yaml`.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
`mysqldump@4.0.0`

**What happened**:
A Secret got generated although I'm using an existing secret.

**What you expected to happen**:
Not to have a superfluous Secret.

**How to reproduce it** (as minimally and precisely as possible):

See bug description.

**Anything else we need to know**:

Additionally I noticed that a new Job is also created (Migrating from `stable/mysqldump@2.6.2`). I'm assuming this is to run a backup as soon as mysqldump is deployed, however the Job doesn't have a [post-install hook etc.](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks) assigned to it, so it's kind of weird.

**Comment by Anticom** [comment]
FYI: I just checked out v3.0.0 of the chart which doesn't seem to have this problem.

**Comment by monotek** [comment]
closed by: https://github.com/kokuwaio/helm-charts/pull/50
