### ISSUE TITLE
monotek/gcloud-mysql:14 broken (images moved to quay.io anyway)

### ISSUE THREAD

**Issue by Anticom** [kokuwaio/helm-charts#42]
**Describe the bug**
Version 3.0.0 of your chart uses `monotek/glcloud-mysql:14` image by default. However this image seems to be broken on docker hub. Further more I've dug up in [this](https://github.com/monotek/gcloud-mysql/issues/4) ticket, that the images have moved to quay.io.
I've seen you've fixed this for 4.0.0 already however it would be nice if it was backported to v3.0.0 as well.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
3.0.0

**What happened**:
See "How to reproduce it" 

**What you expected to happen**:
See "How to reproduce it"

**How to reproduce it** (as minimally and precisely as possible):
```
$ docker pull monotek/gcloud-mysql:14
14: Pulling from monotek/gcloud-mysql
c9b1b535fdd9: Pulling fs layer 
154273e513cd: Pulling fs layer 
933d69b35b6b: Pulling fs layer 
a3f65b977c0a: Waiting 
a7843b48aa70: Waiting 
5bd1f4474bc7: Waiting 
error pulling image configuration: unknown blob
```

**Anything else we need to know**:
I don't want to use v4.0.0 since I don't quite understand what has changed in detail there. But I don't like that mariadb is a dependency that's enabled by default.
If someone is feeling like elaborating on why a helm chart that is supplying a backup mechanism for databases is shipping a database, please go ahead.

**Comment by monotek** [comment]
mariadb is not enabled by default: 
https://github.com/kokuwaio/helm-charts/blob/main/charts/mysqldump/Chart.yaml#L23
i'ts just used for ci.

**Comment by Anticom** [comment]
Alright, sorry. Must have missread my resulting yaml. I've confirmed that
```sh
helm template \
    proof \
    kokuwa/mysqldump \
    --version 4.0.0 \
    --set mysql.host=my-host \
    --set mysql.existingSecret=existing-secret \
    --set mysql.existingSecretKey=existing-secret-key
```
is producing the desired result.
