### ISSUE TITLE
Add "include_timestamp" parameter in case of using ilm index_name instead of logstash_format

### ISSUE THREAD

**Issue by xiaset** [kokuwaio/helm-charts#46]
Hi, could you add the `include_timestamp` field to the output.conf config to add timespamp to documents when using ilm `index_name` instead of `logstash_format`. There is no timestamp field in the elasticsearch documents if `logstash_format` set to `false`

Parameter description:
https://github.com/uken/fluent-plugin-elasticsearch#include_timestamp

configmap.yaml part example:
```
{{- if .Values.elasticsearch.logstash.enabled }}
      logstash_format "#{ENV['LOGSTASH_FORMAT']}"
      logstash_dateformat "#{ENV['LOGSTASH_DATEFORMAT']}"
      logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
      logstash_prefix_separator "#{ENV['LOGSTASH_PREFIX_SEPARATOR']}"
{{- else }}
      include_timestamp true
      logstash_format "#{ENV['LOGSTASH_FORMAT']}"
      index_name "#{ENV['INDEX_NAME']}"
{{- end }}
```

**Comment by monotek** [comment]
Would you mind to create an pr please?
