### ISSUE TITLE
/usr/local/bundle/gems/fluentd-1.11.3/lib/fluent/plugin_helper/http_server/compat/server.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call /usr/local/bundle/gems/fluentd-1.11.3/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here

### ISSUE THREAD

**Issue by zhoubonet** [kokuwaio/helm-charts#5]
/usr/local/bundle/gems/fluentd-1.11.3/lib/fluent/plugin_helper/http_server/compat/server.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/fluentd-1.11.3/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here

**Comment by monotek** [comment]
issue template not used.

**Comment by zhoubonet** [comment]
/usr/local/bundle/gems/fluentd-1.11.3/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here
2020-10-06 03:16:41 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-10-06 03:16:42.786867931 +0000 chunk="5b0f806aaf816e47190bff4ca3750864" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch-master\", :port=>9200, :scheme=>\"http\", :path=>\"\"}): read timeout reached"


template is default
![image](https://user-images.githubusercontent.com/4209701/95155002-bb76aa00-07c5-11eb-81a6-573b8f69d5b7.png)

**Comment by monotek** [comment]
so whats the report? 
that the container, that is not part of this repo, throws a warning, but the logging still works?
