### ISSUE TITLE
[mysqldump] secret-gcp template not working

### ISSUE THREAD

**Issue by jfiedler** [kokuwaio/helm-charts#55]
The secret-gcp template is not working (at all) if you enable gcp storage. The template is referencing a function that is not defined:

> template "mysqldump.gcpsecretName" not defined

As a workaround we need to enable referencing an existing secret (instead of having the chart create it).

**Comment by monotek** [comment]
PR to fix it would be welcome ;-)
If i remember it right, it did work before as we used it this way in the kg clusters?

**Comment by jfiedler** [comment]
It likely worked in much older versions of the chart. Since I ran into subsequent problems (when using existingSecret as workaround) I ended up eliminating the Helm chart completely and go straight to K8s manifests via Flux. Sorry, no PR coming. ;-)

**Comment by monotek** [comment]
fixe via: https://github.com/kokuwaio/helm-charts/pull/58
