### ISSUE TITLE
2020-10-06 14:26:00 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Invalid Kubernetes API v1 endpoint https://172.21.0.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get issuer certificate)"

### ISSUE THREAD

**Issue by zhoubonet** [kokuwaio/helm-charts#6]
Remove below Is OK

![image](https://user-images.githubusercontent.com/4209701/95215014-17bbe700-0823-11eb-8cf1-6bf1e2b95bb8.png)

**Comment by monotek** [comment]
Could you please just stop creating tickets ignoring our issue template?! 

Your issues are not even issues. We had 2 warnings and 1 kubernetes error now. All this with just the error message in issue subject and body. This does not help us. It creates work.
