### ISSUE TITLE
[mysqldump] upload.googlestoragebucket.existingSecret is not used

### ISSUE THREAD

**Issue by elwood218** [kokuwaio/helm-charts#64]
**Describe the bug**
The value `upload.googlestoragebucket.existingSecret` is never set when mounting volumes in pod. The `secretName` is always set to 

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
4.0.3

**What happened**:
Setting `upload.googlestoragebucket.existingSecret` is ignored and pod complains about secret not found.

**What you expected to happen**:
The secret I have already created is used with the name which I set in `upload.googlestoragebucket.existingSecret`.

**How to reproduce it** (as minimally and precisely as possible):

<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```
upload:
  googlestoragebucket:
    enabled: true
    bucketname: "<Bucketname>"
    jsonKeyfile: ""
    secretFileName: "keyfile.json"
    existingSecret: "mysqldump-sa"
    serviceAccountName: "mysqldump"
```

```
helm install my-release {{ .GitHubOrg }}/name-of-chart --version version --values values.yaml
```

-->

**Anything else we need to know**:

**Comment by monotek** [comment]
will be fixed with: https://github.com/kokuwaio/helm-charts/pull/65
