### ISSUE TITLE
Add ability to inject secrets from vault as environmental variable

### ISSUE THREAD

**Issue by rileyhun** [kokuwaio/helm-charts#66]
Hello - I've stored my elasticsearch password in Google Secret Manager. I have set-up a mutating webhook configuration called [Berglas](https://github.com/GoogleCloudPlatform/berglas/tree/main/examples/kubernetes) that allows targeted pods to reference the secret in Google Secret Manager as an environmental variable. Is there a way to inject this into the fluentd pods through the helm chart config?

Additionally, when I try to add a service account (necessary to connect to Google Secret Manager), it results in this error:

```
Error creating: pods "fluentd-fluentd-elasticsearch-" is forbidden: error looking up service account logging/fluentd-fluentd-elasticsearch: serviceaccount "fluentd-fluentd-elasticsearch" not found
```

**Comment by monotek** [comment]
https://github.com/kokuwaio/helm-charts/blob/main/charts/fluentd-elasticsearch/values.yaml#L156

**Comment by rileyhun** [comment]
> https://github.com/kokuwaio/helm-charts/blob/main/charts/fluentd-elasticsearch/values.yaml#L156

Thanks. I tried setting it as an environmental variable, but it wasn't accepting the secret stored in secret manager. It was referencing the literal string of the path.
