### ISSUE TITLE
Add helm chart variable to set fluentd's own log output format

### ISSUE THREAD

**Issue by Ghazgkull** [kokuwaio/helm-charts#74]
**Is your feature request related to a problem? Please describe.**
Fluentd allows clients to configure the format of its own logging as either text or json as documented here: https://docs.fluentd.org/deployment/logging#log-format

Currently, enabling json logging with the helm chart is possible but it requires setting the flag to disable the default system config and then providing your own. We should add a simple flag to the helm chart to allow folks to easily set the logging format.

I can put together a PR with an implementation of this.

**Comment by monotek** [comment]
PR would be welcome :)
