### ISSUE TITLE
Could not communicate to Elasticsearch, resetting connection and trying again. no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by MarkKharitonov** [kokuwaio/helm-charts#9]
**Describe the bug**
Having installed elasticsearch and kibana following the instructions on https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-quickstart.html#k8s-quickstart I tried to install fluentd-elasticsearch using the provided [values.yaml](https://github.com/kokuwaio/helm-charts/blob/main/charts/fluentd-elasticsearch/values.yaml) with certain modifications.

Basically I:

1. Uncommented the resources values
1. Enabled `elasticsearch.auth` (not sure if I was supposed to, since it is `false` by default) and provided the elastic user and password.
1. Modified the hosts value. I used the elasticsearch http service name as the host.

The fluentd pods are unable to communicate to elasticsearch and are being restarted all the time. The log message is:
```
2020-10-10 15:18:45 +0000 [warn]: [elasticsearch] Could not communicate to Elasticsearch, resetting connection and trying again. no implicit conversion of nil into String (TypeError)
```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T18:49:11Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
```
helm list -n elastic
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
fluentd-elasticsearch   elastic         1               2020-10-10 11:05:22.8275824 -0400 EDT   deployed        fluentd-elasticsearch-10.0.2    3.0.5
```

**What happened**:

I ran the command line `helm install fluentd-elasticsearch kokuwa/fluentd-elasticsearch -n elastic -f .\values.yaml` and soon after when I was checking the fluentd pods I noticed the error in the logs.

**What you expected to happen**:

The pods work without being restarted.

**How to reproduce it** (as minimally and precisely as possible):

Not clear, I just installed elasticsearch and kibana into elastic namespace and then installed the helm chart using my values.yaml.

Here is my values.yaml changes:
```
resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi
    enabled: true
    user: "elastic"
    password: *** The elastic user password ***
  hosts: ["elasticsearch-es-http:9200"]
```

**Anything else we need to know**:
```
C:\> k get all -n elastic
NAME                                    READY   STATUS    RESTARTS   AGE
pod/elasticsearch-es-default-0          1/1     Running   0          11d
pod/elasticsearch-kb-779666b648-rxtqf   1/1     Running   0          11d
pod/fluentd-elasticsearch-2lb9t         1/1     Running   0          113s
pod/fluentd-elasticsearch-7tw4r         1/1     Running   0          113s
pod/fluentd-elasticsearch-hn7cb         1/1     Running   0          113s
pod/fluentd-elasticsearch-k4cxg         1/1     Running   0          113s
pod/fluentd-elasticsearch-mpfzv         1/1     Running   0          113s
pod/fluentd-elasticsearch-wv59x         1/1     Running   0          113s

NAME                                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/elasticsearch-es-default     ClusterIP   None           <none>        9200/TCP   11d
service/elasticsearch-es-http        ClusterIP   10.0.26.60     <none>        9200/TCP   11d
service/elasticsearch-es-transport   ClusterIP   None           <none>        9300/TCP   11d
service/elasticsearch-kb-http        ClusterIP   10.0.223.179   <none>        5601/TCP   11d

NAME                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/fluentd-elasticsearch   6         6         6       6            6           <none>          114s

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/elasticsearch-kb   1/1     1            1           11d

NAME                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/elasticsearch-kb-779666b648   1         1         1       11d

NAME                                        READY   AGE
statefulset.apps/elasticsearch-es-default   1/1     11d
C:\>
```

I must be doing something wrong, but I do not understand what exactly.

**Comment by monotek** [comment]
If you port forward to the same address can you reach es?

**Comment by MarkKharitonov** [comment]
I have destroyed the cluster to try other things, but I can assert that both elastic search and kibana port forwarding work as expected - the ES returned a JSON payload with some fields and a message "For the search,.. you know" or something like that. Kibana presented with a Web portal. In both cases ES credentials were required - the same ones I provided to fluentd in values.yaml.

**Comment by monotek** [comment]
Ok, so closing this for now.

Next time please provide some more Infos. If the cluster status is green would be important info too.

Having a look at your values file shows wrong indent for the auth values too.

**Comment by sd-hd** [comment]
Same error here. 

The solution was to add "https://" to the host-url in the helm values.yaml

e.g. https://elasticsearch-es-http.elastic-system.svc.cluster.local:9200

**Comment by fil-monterey** [comment]
Thanks @sd-hd 
using https scheme helped me as shown below:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/7454739/114439596-27800380-9b97-11eb-8edc-87e89b1cca5d.png">
